global using Microsoft.EntityFrameworkCore;
global using ChatAppWithSignalR.Api.Functions.User;
global using ChatAppWithSignalR.Api.Functions.UserFriend;
global using ChatAppWithSignalR.Api.Functions.Message;
global using ChatAppWithSignalR.Api.Entities;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc;
global using ChatAppWithSignalR.Api.Helpers;
global using Microsoft.AspNetCore.SignalR;